/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gameoflife;

import java.util.ArrayList;

public class App {

    public static void main(String[] args) throws InterruptedException {
        InputReader inputReader = new InputReader();
        ArrayList<ArrayList<Integer>> grid = inputReader.readInputFromFile();
        if (grid.size() == 0) {
            System.exit(0);
        }

        Grid nextGenerationGrid = new Grid(grid);
        int t = 500000;
        while (t > 0) {
            System.out.println("\033[2J\033[1;1H");
            nextGenerationGrid.printGrid();
            t--;
            Thread.sleep(1000);
        }
    }
}
