/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GameOfLife;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        String actualOutput = classUnderTest.getGreeting();
        assertEquals("Hello World", actualOutput);
    }
}
